site_name: About CivBot — discord bot for Civilization V game.
site_url: https://djimontyp.github.io/CivBot-docs/

nav:
  - CivBot: index.md
  - Rating: rating.md
#  - Features:
#    - Game:
#      - Create: commands/game_create.md
#      - Join: commands/game_join.md
#      - Kick: commands/game_kick.md
#      - Leave: commands/game_leave.md
#      - Refresh: commands/game_refresh.md
#  - Config: config.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  icon:
    translate: fontawesome/regular/globe
  language: en
  features:
    - navigation.tabs
#    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.path
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  extra_css:
    - stylesheets/extra.css
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to system preference

plugins:
  - search
  - mkdocstrings
  - tags
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          default: true

        - locale: uk
          name: Ukrainian
          build: true
          site_name: CivBot — discord bot для гри Civilization V.
          nav_translations:
            Features: Функціонал
            Rating: Рейтинг
            Game: Гра
            Create: Створити
            Join: Приєднатися
            Leave: Покинути
            Kick: Вигнати
            Refresh: Оновити
            Config: Налаштування

        - locale: ru
          name: Russian
          build: true
          site_name: CivBot — discord bot для игры Civilization V.
          nav_translations:
            Features: Функционал
            Rating: Рейтинг
            Game: Игра
            Create: Создать
            Join: Присоединиться
            Leave: Покинуть
            Kick: Выгнать
            Refresh: Обновить
            Config: Настройки




extra:
  analytics:
    provider: google
    property: G-FJ3QBDSVV9

markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; 2023 <a href="https://maks-naumenko.com"  target="_blank" rel="noopener">Maks Naumenko</a>