site_name: About CivBot — discord bot for Civilization V game.
site_url: https://djimontyp.github.io/CivBot-docs/

nav:
  - CivBot: index.md
  - Getting started: getting_started.md
  - Commands:
    - /game:
      - create: commands/game_create.md
      - join: commands/game_join.md
      - leave: commands/game_leave.md
      - kick: commands/game_kick.md
      - refresh: commands/game_refresh.md
  - States: states.md
  - Config: config.md

theme:
  icon:
    logo: fontawesome/solid/robot
    translate: fontawesome/regular/globe
  language: en
  name: material
  features:
    - navigation.tabs
#    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.path
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: orange
      accent: red
    - scheme: grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: orange

plugins:
  - search
  - mkdocstrings
  - tags
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          default: true

        - locale: uk
          name: Ukrainian
          build: true
          site_name: CivBot — discord bot для гри Civilization V.
          nav_translations:
            Commands: Команди
            Getting started: Початок роботи
            /game: /гра
            create: створити
            join: приєднатися
            leave: покинути
            kick: вигнати
            refresh: оновити
            States: Стани
            Config: Налаштування

        - locale: ru
          name: Russian
          build: true
          site_name: CivBot — discord bot для игры Civilization V.
          nav_translations:
            Commands: Команды
            Getting started: Начало работы
            /game: /игра
            create: создать
            join: присоединиться
            leave: покинуть
            kick: выгнать
            refresh: обновить
            States: Статусы
            Config: Настройки



extra:
  analytics:
    provider: google
    property: G-FJ3QBDSVV9

markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; 2023 <a href="https://maks-naumenko.com"  target="_blank" rel="noopener">Maks Naumenko</a>